---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WHU-LiXiaoJian.
--- DateTime: 2023/3/31 22:15
---
--- 比较线程标识与锁中的线程标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    --- 释放锁
    return redis.call('del', KEYS[1])
end
return 0